// <auto-generated />
using System;
using Hamroh_V2.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Hamroh_V2.Data.Migrations
{
    [DbContext(typeof(Hamroh_V2DbContext))]
    [Migration("20221114093043_firstMig")]
    partial class firstMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Hamroh_V2.Domain.Entities.Clients.Client", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<int>("PeopleCount")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Qayerdan")
                        .HasColumnType("text");

                    b.Property<string>("Qayerga")
                        .HasColumnType("text");

                    b.Property<string>("Summa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Hamroh_V2.Domain.Entities.DriverAds.DriverAd", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Amenities")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Qayerdan")
                        .HasColumnType("text");

                    b.Property<string>("Qayerga")
                        .HasColumnType("text");

                    b.Property<string>("Summa")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DriverAds");
                });

            modelBuilder.Entity("Hamroh_V2.Domain.Entities.Drivers.Driver", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("CarImage")
                        .HasColumnType("text");

                    b.Property<string>("CarName")
                        .HasColumnType("text");

                    b.Property<long?>("DriverAdId")
                        .HasColumnType("bigint");

                    b.Property<string>("DriverImage")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DriverAdId");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Hamroh_V2.Domain.Entities.Drivers.Driver", b =>
                {
                    b.HasOne("Hamroh_V2.Domain.Entities.DriverAds.DriverAd", null)
                        .WithMany("DriverData")
                        .HasForeignKey("DriverAdId");
                });

            modelBuilder.Entity("Hamroh_V2.Domain.Entities.DriverAds.DriverAd", b =>
                {
                    b.Navigation("DriverData");
                });
#pragma warning restore 612, 618
        }
    }
}
